### ISSUE TITLE
Instructions / Script for compiling in Windows.

### ISSUE THREAD

**Issue by XfedeX** [ArtFect/Proxy-Server#4]
When I try to generate sources for Eclipse or building, i get error `java.lang.IllegalArgumentException: Unsupported class file major version 60`.
A nice, pre-done build script would probably fix that.

Also this needs a decent readme.

**Comment by ArtFect** [comment]
What's your version of java? If 16, then probably an error due to the fact that gradle does not support it
https://github.com/gradle/gradle/issues/14273

This mod can be imported and built in the same way as all other mods for the fabric
https://fabricmc.net/wiki/tutorial:setup

In IDEA, it's just import "build.gradle", wait for gradle to do everything and select on the right: Gradle -> %project_name% -> Tasks -> build -> build
